### PR TITLE
0.26: Support native B::OP::parent with 5.21.2 -DPERL_OP_PARENT

### PR DESCRIPTION
**Pull request by rurban**

### CODE REVIEW

**Comment by karenetheridge** [comment]
This looks good to me, but I was unsure of merging it for 0.26 without hearing from the module author. (@jbenjore, are you still around?)

Note - this fixes https://rt.cpan.org/Ticket/Display.html?id=100251

**Comment by rurban** [comment]
I'll release it soon.  I just need to check more parent/sibling issues first

**Comment by rurban** [comment]
Josh, can you have a look? Since I don't want to fight p5p which just took the `parent` method and 
returns `B::NULL` or the real parent for some interim releases, I added the `_parent` method which does the right thing.
Passes all tests on all versions and variants, esp. -DPERL_OP_PARENT.

We might add a better fallback name for parent: `uparent` maybe (for "utils parent")?

On the other hand this is only needed for 5.21.2 - 5.21.11. With core https://github.com/Perl/perl5/commit/1fafe688be3ff13b81d5e18b2a8766dd719ee8eb from 5.21.12 the new core parent will be undefined again, so we can keep our parent method.

**Comment by karenetheridge** [comment]
Is this safe to merge, or should it be changed somehow?

**Comment by haarg** [comment]
@rurban will your `_parent` method always return the same thing as the core `parent` method when `PERL_OP_PARENT` is defined?  Maybe naming it something like `find_parent` would be reasonable.

**Comment by rurban** [comment]
@haarg: As I said. the only difference is for  5.21.2 - 5.21.11, returning B::NULL for an undefined parent. We should not care for those versions, and will return undef for no parent.
Thus the new _parent method is not really needed, as p5p was able to fix it in time.

**Comment by neilb** [comment]
How about defining a new method called something like `parent_node`, or as you suggested (Reini), `uparent`. That could be documented, and for old releases of perl, alias `parent` to `parent_node()`?

**Comment by rurban** [comment]
Uploaded 0.26 to CPAN, but forgot that I got no perms.
Please merge to upstream also.

**Comment by neilb** [comment]
@rurban you're probably aware of this already/now, but there's already a 0.26 on CPAN, released by ETHER.

**Comment by rurban** [comment]
I'm giving up. 
How come that random incompetent people just get perms to upload stuff, without any coordination?
This is now the 2nd time, after the Sub::Name desaster

**Comment by karenetheridge** [comment]
@rurban: on distributions with multiple maintainers, it is expected that people look on CPAN first to see what has been uploaded. Since you didn't do that, I think that makes you the incompetent one, not me.

If I made a mistake with B-Utils, please be specific as to what.

**Comment by shadowcat-mst** [comment]
@rurban because jjore gave me permission some time ago to hand out co-maint for interim releases of things as required, as did many other people.

As such, it isn't random incompetent people, it's specific incompetent people selected because they're happy to admit to their incompetence and fix things, rather than screaming insults like an angry toddler as seems to be your specialty.

Any time you want to start acting like an adult, I'd be happy to add you to the list of people I'll consider letting have access to things; until then, I'd rather have ether getting it wrong than you getting it right because it'll still be a more pleasant experience for contributors and users.

**Comment by karenetheridge** [comment]
@rurban I cannot apply your changes, as tests fail (on 5.22.0):

```
t/utils/30parent.t .................. 1/181 
#   Failed test 'No parent for root leavesub-UNOP=(0x7fa9c085cae0)'
#   at t/utils/30parent.t line 64.
#          got: 'B::NULL=SCALAR(0x7fa9c09f9418)'
#     expected: undef
Can't locate object method "kids" via package "B::NULL" at t/utils/30parent.t line 72.
# Looks like you planned 181 tests but ran 2.
# Looks like you failed 1 test of 2 run.
# Looks like your test exited with 255 just after 2.
t/utils/30parent.t .................. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 180/181 subtests 
```

Your changes, merged on top of the indexed 0.26 release, are here for your verification: https://github.com/karenetheridge/B-Utils/tree/topic/rurban_0.26

Please let me know when you have a fix, or if I made an error with the merge.

**Comment by karenetheridge** [comment]
@rurban could you please delete your 0.26 release from PAUSE? cpantesters does not store test results by PAUSE id, only distname + version, so the 5.22 failures in your release are going to clash with the indexed 0.26. Thanks!

**Comment by karenetheridge** [comment]
@rurban Your commit 330d18e does not run on perl 5.21.x and higher:

```
: [ether@jaeger git/B-Utils]$; perl -Mblib t/utils/30parent.t 
1..181
not ok 1 - No parent for root leavesub-UNOP=(0x7fafa11104e0)
#   Failed test 'No parent for root leavesub-UNOP=(0x7fafa11104e0)'
#   at t/utils/30parent.t line 64.
#          got: 'B::NULL=SCALAR(0x7fafa1275650)'
#     expected: undef
ok 2 - lineseq-LISTOP=(0x7fafa1009a20) has a parent
Can't locate object method "kids" via package "B::NULL" at t/utils/30parent.t line 72.
# Looks like you planned 181 tests but ran 2.
# Looks like you failed 1 test of 2 run.
# Looks like your test exited with 255 just after 2.
```

Please advise?

**Comment by karenetheridge** [comment]
I'm going over your changes again now to find the discrepancies. I think I've found it; will release as 0.27.

**Comment by rurban** [comment]
The problem is the B::OP::parent bug returning now B::NULL instead of undef. 
Representing no parent as an B::NULL object is not just an API change, it is a bug.
And upstream will not fix as far as I know them.

I thought of getting along with using B::Utils _parent in 748a5b2aaed9, 
but B::OP::parent needs to be patched, to do the right thing. 
Which is equally horrible.

The discrepancies are very prominently documented BTW.

**Comment by rurban** [comment]
I forked it now to B::Utils1, with all the bugs fixed, and keep B::OP->parent returning undef instead of B::NULL.
Good luck with this version. 
I do not trust ether with the maintenance of this module, so it's better to have two seperate versions.

**Comment by karenetheridge** [comment]
@rurban I'm just applying patches as I receive them, and @jbenjore is still a maintainer of this module as well. Do you have a patch to provide, or just insults? :/

**Comment by ribasushi** [comment]
In what way is `I do not trust <insert name> with the maintenance of this module` an insult?

**Comment by shadowcat-mst** [comment]
@ribasushi in light of the 'random incompetent people' crap earlier, one would expect it to be taken that way,

Anyway, I guess we'll find somebody who actually wants to help rather than fling poo and see where we go from there.

**Comment by rurban** [comment]
> On Jul 24, 2015, at 6:05 PM, Karen Etheridge notifications@github.com wrote:
> 
> @rurban I'm just applying patches as I receive them,

So you really think your are qualified to apply patches “as our receive them”?

> and @jbenjore is still a maintainer of this module as well. Do you have a patch to provide, or just insults? :/

Which insults?

I don’t trust your ability to maintain code you have no idea of, and I don’t want to change the old API for parents, 
and I don’t want to use two checks where one is needed.
So I had to fork it. No problem. 
Maybe you are happy to go with the new p5p API, and I am not. But most likely you have no idea what I was talking about.

The problem started when someone gave you maintainership.
Same as with Sub::Name which you also are not qualified to maintain, 
and your previous modules which you took over and then started to destroy 
for reasons whatssoever. For sure not technical.

It’s much better if I keep out of your way and keep it together. I’m actually using those modules.
Have a nice day with your new module

**Comment by karenetheridge** [comment]
> So you really think your are qualified to apply patches “as our receive them”?

If they are from you, or another p5porter, yes, if the patch contains tests and the reasoning is clear. I consult with others when I am not sure, as I did a few days ago with B::Hooks::Parser.

If you are capable of engaging with me as an adult and explaining the problems you see, I'm sure we can work something out. But simply saying that I am "destroying" things is not helpful, as I have nothing to go on. Can you be civil, please?

**Comment by rurban** [comment]
I already told you at https://github.com/jbenjore/B-Utils/pull/10#issuecomment-113104431 that I was giving up. There was enough time. There's no way that this could work. Go your way but don't interfere in things you have no idea about, please. It doesn't help. I need stable API's and modules, and I'm not willing to deal with yet another incompetent maintainer "who is just willing to help". (I'm not meaning josh here, of course)

**Comment by karenetheridge** [comment]
@rurban could you please clarify what problems exist with Sub::Name? I'm not aware of any problem reports. If you're referring to the 3 open pull requests, as I understand it you, @ribasushi and @aristotle are still discussing the right way forward?

**Comment by rurban** [comment]
No, discuss it over there.

The context:
You interfered there also by taking over Sub::Name and didn't fix the outstanding issues. Why did you feel you should do that? I not only provided the needed features, I also fixed it. But you let it rest, and you still have no idea how to solve it. @ribasushi and @aristotle will not solve it for you. This is not maintenance, this is destruction by incompetence and agony. 
Thanksfully I don't care about Sub::Name. But I do care about B and B::Utils. Hence the fork.

**Comment by rurban** [comment]
2015-07-24 18:10 GMT+02:00 Peter Rabbitson notifications@github.com:

> In what way is I do not trust <insert name> with the maintenance of this
> module an insult?
> 
> This is not an insult. This is a qualified statement of the problems with
> these maintainership perms. It didn't work before and it will not work in
> the foreseeable future. I don't care if she restricts Moose and "Modern
> Perl", but I do care about important "core" modules.

I blogged about the 5.6 problems with this maintainership style before
also, but refrain from doing so now, even if you requested so. Everybody
who is able to run benchmarks would see the point. And I don't want to
repeat myself in a loaded athmosphere.
Maybe one argument for you: Security and maintenance got worse, not better,
since 5.6. Not only memory and speed performance and the ability to
implement features went down.
I saw that you think otherwise, but I honestly cannot follow this

## argumentation of yours.

Reini

**Pull request closed without merging**
